### ISSUE TITLE
VSCode R ：use plotly can't not download png

### ISSUE THREAD

**Issue by Achuan-2** [renkun-ken/using-rstats-in-vscode#1]
sorry there was a problem downloading your snapshot!
![image](https://user-images.githubusercontent.com/60436214/144878338-d61f5b4a-54ab-4fdd-b48b-f7612271ac3d.png)

so what's the problem

**Comment by renkun-ken** [comment]
Please raise issue at <https://github.com/REditorSupport/vscode-R/issues>.
